### ISSUE TITLE
Error when running ServiceConfigTest on Windows machine

### ISSUE THREAD

**Issue by ales-kunst** [apssouza22/trading-system#15]
Hello,

I have found that when I run ServiceConfigTest test on the Windows machine I get the following error:
```
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/drive_d/programming/projects/java/scrapbook/trading-system/common/target/test-classes//properties.test.yml

	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.apssouza.mytrade.common@1.0-SNAPSHOT/com.apssouza.mytrade.common.appconfig.ServiceConfig.load(ServiceConfig.java:40)
	at com.apssouza.mytrade.common@1.0-SNAPSHOT/com.apssouza.mytrade.common.appconfig.ServiceConfigTest.test_load(ServiceConfigTest.java:17)
```
The problem is probably in your ServiceConfigTest inside of the test_load() method in line 17 where you have written the following line:
`ConfigurationProvider provider = ServiceConfig.load(uri.getPath(), "test");`

I think that the better solution would be to have it in this way:
`ConfigurationProvider provider = ServiceConfig.load(Paths.get(uri).toString(), "test");`

Cheers,
Ales

**Comment by apssouza22** [comment]
Hi @ales-kunst thanks for the suggestion. WOuld you be able to open an PR with the change, please?

**Comment by ales-kunst** [comment]
Can you please merge pull request #16 into your codebase.
